# Generated by Django 2.2.6 on 2020-10-16 04:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20201016_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 4, 46, 17, 469954, tzinfo=utc), verbose_name='%Y-%m-%d %H:%M:%S'),
        ),
    ]
