# Generated by Django 2.2.6 on 2020-10-16 05:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20201016_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 5, 53, 19, 810305, tzinfo=utc), verbose_name='%Y-%m-%d %H:%M:%S'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
    ]
