# Generated by Django 2.2.6 on 2020-09-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
