# Generated by Django 2.2.6 on 2020-09-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='popularity_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
